using System;
using System.Collections.Generic;
using System.Text;

namespace CsLightDbGen.SQLiteGenerator;

public class GeneratorJsonUtils
{

    internal const string LdgSQLiteUtils = $$$"""
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a tool.
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        
        #nullable enable

        using System.Collections.Generic;
        using System.Diagnostics.CodeAnalysis;
        using System.Text.Json;
                        
        namespace CsLightDbGen.SQLiteGenerator
        {
            public static class LdgSQLiteUtils
            {
                public enum LdgNumericOperatorCodes : int
                {
                    Equals = 0,
                    NotEquals = 1,
                    GreaterThan = 2,
                    GreaterThanOrEquals = 3,
                    LessThan = 4,
                    LessThanOrEquals = 5,
                }
                
                public static string GetSqlOperator(LdgNumericOperatorCodes op) => op switch
                {
                    LdgNumericOperatorCodes.Equals => "=",
                    LdgNumericOperatorCodes.NotEquals => "!=",
                    LdgNumericOperatorCodes.GreaterThan => ">",
                    LdgNumericOperatorCodes.GreaterThanOrEquals => ">=",
                    LdgNumericOperatorCodes.LessThan => "<",
                    LdgNumericOperatorCodes.LessThanOrEquals => "<=",
                    _ => throw new NotSupportedException($"Unsupported operator code: {op}"),
                };
            
                private static System.Text.RegularExpressions.Regex _htmlStripRegex = new("<.*?>", System.Text.RegularExpressions.RegexOptions.Compiled);

                private static JsonSerializerOptions _options = new JsonSerializerOptions()
                {
                    WriteIndented = false,
                };

                public static bool TrySerializeForDb<T>(T? instance, [NotNullWhen(true)]out string? json) where T : class
                {
                    if (instance == null)
                    {
                        json = null;
                        return false;
                    }

                    json = JsonSerializer.Serialize(instance, _options);
                    return true;
                }

                public static bool TrySerializeForDb<T>(List<T>? instances, [NotNullWhen(true)] out string? json) where T : class
                {
                    if ((instances == null) || (instances.Count == 0))
                    {
                        json = null;
                        return false;
                    }

                    json = JsonSerializer.Serialize(instances, _options);
                    return true;
                }

                public static T? ParseFromDb<T>(string json) where T : class
                {
                    if (string.IsNullOrWhiteSpace(json))
                    {
                        return null;
                    }

                    return JsonSerializer.Deserialize<T>(json, _options);
                }

                public static List<T> ParseArrayFromDb<T>(string json) where T : class
                {
                    if (string.IsNullOrWhiteSpace(json))
                    {
                        return new List<T>();
                    }

                    return JsonSerializer.Deserialize<List<T>>(json, _options) ?? [];
                }

                public static string StripHtml(string? input)
                {
                    if (string.IsNullOrWhiteSpace(input))
                    {
                        return string.Empty;
                    }

                    return _htmlStripRegex.Replace(input, string.Empty).Trim();
                }
            }
        }
        #nullable restore
        """;
}
